version: "3"
services:
  backend: 
    image: refael17/my-backend:latest
    container_name: back-compose
    ports:
      - "8080:5000"
    environment:
      - CURRENT_ENVIRONMENT=dev
    volumes:
      - ./back/logs:/app/logs

  frontend:
    image: refael17/my-frontend:latest
    container_name: front-compose
    ports:
      - "8081:80"
    environment:
      - WS_BACK_URL=http://localhost:8080